[package]
name = "etest"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
wgpu = ["dep:egui-wgpu", "dep:pollster", "dep:image"]
snapshot = ["dep:dify", "dep:dify_image"]

[dependencies]
accesskit_consumer = "0.24.0"
accesskit_query = { path = "../accesskit_query" }
egui = { workspace = true, features = ["accesskit"] }

# wgpu dependencies
egui-wgpu = { workspace = true, optional = true }
pollster = { version = "0.3", optional = true }
image = { workspace = true, optional = true }

# snapshot dependencies
dify = { version = "0.6.0", optional = true }
# unfortunately dify hasn't been updated image to 0.25 yet
dify_image = { version = "0.24", package = "image", optional = true }

[dev-dependencies]
wgpu = { workspace = true, features = ["metal"] }
image = { workspace = true, features = ["png"] }
egui = { workspace = true, features = ["default_fonts"] }

[lints]
workspace = true
