[package]
name = "accesskit_query"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accesskit_consumer = "0.24.0"
accesskit = "0.16.0"
extension-traits = "2"

[lints]
workspace = true
